name: Build A2N Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          bc \
          bison \
          flex \
          libssl-dev \
          libelf-dev \
          python3

    - name: Create config
      run: |
        make ARCH=arm64 exynos8895-dreamlte_defconfig

    - name: Build kernel
      run: |
        make ARCH=arm64 -j$(nproc)

    - name: Upload Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: |
          arch/arm64/boot/Image
          arch/arm64/boot/Image.gz
